export const COUNTRIES = [
  { value: 'EG', label: 'Egypt 🇪🇬' },
  { value: 'SA', label: 'Saudi Arabia 🇸🇦' },
  { value: 'AE', label: 'United Arab Emirates 🇦🇪' },
  { value: 'US', label: 'United States 🇺🇸' },
  { value: 'GB', label: 'United Kingdom 🇬🇧' },
  { value: 'DE', label: 'Germany 🇩🇪' },
  { value: 'FR', label: 'France 🇫🇷' },
  { value: 'IT', label: 'Italy 🇮🇹' },
  { value: 'ES', label: 'Spain 🇪🇸' },
  { value: 'CA', label: 'Canada 🇨🇦' },
  { value: 'AU', label: 'Australia 🇦🇺' },
  { value: 'JP', label: 'Japan 🇯🇵' },
  { value: 'CN', label: 'China 🇨🇳' },
  { value: 'IN', label: 'India 🇮🇳' },
  { value: 'BR', label: 'Brazil 🇧🇷' },
  { value: 'RU', label: 'Russia 🇷🇺' },
  { value: 'MX', label: 'Mexico 🇲🇽' },
  { value: 'KR', label: 'South Korea 🇰🇷' },
  { value: 'NL', label: 'Netherlands 🇳🇱' },
  { value: 'SE', label: 'Sweden 🇸🇪' },
  { value: 'NO', label: 'Norway 🇳🇴' },
  { value: 'DK', label: 'Denmark 🇩🇰' },
  { value: 'FI', label: 'Finland 🇫🇮' },
  { value: 'CH', label: 'Switzerland 🇨🇭' },
  { value: 'AT', label: 'Austria 🇦🇹' },
  { value: 'BE', label: 'Belgium 🇧🇪' },
  { value: 'PT', label: 'Portugal 🇵🇹' },
  { value: 'GR', label: 'Greece 🇬🇷' },
  { value: 'PL', label: 'Poland 🇵🇱' },
  { value: 'CZ', label: 'Czech Republic 🇨🇿' },
  { value: 'HU', label: 'Hungary 🇭🇺' },
  { value: 'RO', label: 'Romania 🇷🇴' },
  { value: 'BG', label: 'Bulgaria 🇧🇬' },
  { value: 'HR', label: 'Croatia 🇭🇷' },
  { value: 'SI', label: 'Slovenia 🇸🇮' },
  { value: 'SK', label: 'Slovakia 🇸🇰' },
  { value: 'EE', label: 'Estonia 🇪🇪' },
  { value: 'LV', label: 'Latvia 🇱🇻' },
  { value: 'LT', label: 'Lithuania 🇱🇹' },
  { value: 'IE', label: 'Ireland 🇮🇪' },
  { value: 'IS', label: 'Iceland 🇮🇸' },
  { value: 'TR', label: 'Turkey 🇹🇷' },
  { value: 'JO', label: 'Jordan 🇯🇴' },
  { value: 'LB', label: 'Lebanon 🇱🇧' },
  { value: 'SY', label: 'Syria 🇸🇾' },
  { value: 'IQ', label: 'Iraq 🇮🇶' },
  { value: 'KW', label: 'Kuwait 🇰🇼' },
  { value: 'QA', label: 'Qatar 🇶🇦' },
  { value: 'BH', label: 'Bahrain 🇧🇭' },
  { value: 'OM', label: 'Oman 🇴🇲' },
  { value: 'YE', label: 'Yemen 🇾🇪' },
  { value: 'MA', label: 'Morocco 🇲🇦' },
  { value: 'TN', label: 'Tunisia 🇹🇳' },
  { value: 'DZ', label: 'Algeria 🇩🇿' },
  { value: 'LY', label: 'Libya 🇱🇾' },
  { value: 'SD', label: 'Sudan 🇸🇩' },
  { value: 'ZA', label: 'South Africa 🇿🇦' },
  { value: 'NG', label: 'Nigeria 🇳🇬' },
  { value: 'KE', label: 'Kenya 🇰🇪' },
  { value: 'ET', label: 'Ethiopia 🇪🇹' },
  { value: 'GH', label: 'Ghana 🇬🇭' },
  { value: 'TH', label: 'Thailand 🇹🇭' },
  { value: 'VN', label: 'Vietnam 🇻🇳' },
  { value: 'MY', label: 'Malaysia 🇲🇾' },
  { value: 'SG', label: 'Singapore 🇸🇬' },
  { value: 'ID', label: 'Indonesia 🇮🇩' },
  { value: 'PH', label: 'Philippines 🇵🇭' },
  { value: 'NZ', label: 'New Zealand 🇳🇿' },
  { value: 'AR', label: 'Argentina 🇦🇷' },
  { value: 'CL', label: 'Chile 🇨🇱' },
  { value: 'CO', label: 'Colombia 🇨🇴' },
  { value: 'PE', label: 'Peru 🇵🇪' },
  { value: 'VE', label: 'Venezuela 🇻🇪' },
  { value: 'UY', label: 'Uruguay 🇺🇾' },
  { value: 'EC', label: 'Ecuador 🇪🇨' },
  { value: 'BO', label: 'Bolivia 🇧🇴' },
  { value: 'PY', label: 'Paraguay 🇵🇾' },
  { value: 'PK', label: 'Pakistan 🇵🇰' },
  { value: 'BD', label: 'Bangladesh 🇧🇩' },
  { value: 'LK', label: 'Sri Lanka 🇱🇰' },
  { value: 'NP', label: 'Nepal 🇳🇵' },
  { value: 'MM', label: 'Myanmar 🇲🇲' },
  { value: 'KH', label: 'Cambodia 🇰🇭' },
  { value: 'LA', label: 'Laos 🇱🇦' },
  { value: 'MN', label: 'Mongolia 🇲🇳' },
  { value: 'KZ', label: 'Kazakhstan 🇰🇿' },
  { value: 'UZ', label: 'Uzbekistan 🇺🇿' },
  { value: 'GE', label: 'Georgia 🇬🇪' },
  { value: 'AM', label: 'Armenia 🇦🇲' },
  { value: 'AZ', label: 'Azerbaijan 🇦🇿' }
] as const;

export type CountryCode = typeof COUNTRIES[number]['value'];